name: tubes_tahap_2_mobile_sistem_poin_pelanggaran
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  http: 1.6.0
  shared_preferences: ^2.1.1
  mime: ^1.0.2
  path: ^1.8.3
  intl: ^0.18.0
  collection: ^1.17.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_functions: ^6.0.4
  image_picker: ^0.8.7+5
  file_picker: ^8.0.0
  csv: ^5.0.0
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
