// Mocks generated by Mockito 5.4.6 from annotations
// in tubes_tahap_2_mobile_sistem_poin_pelanggaran/test/white_box/tc_fr_011_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tubes_tahap_2_mobile_sistem_poin_pelanggaran/models/sanction.dart'
    as _i4;
import 'package:tubes_tahap_2_mobile_sistem_poin_pelanggaran/services/sanction_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SanctionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSanctionService extends _i1.Mock implements _i2.SanctionService {
  MockSanctionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Sanction>> streamSanctions() =>
      (super.noSuchMethod(
            Invocation.method(#streamSanctions, []),
            returnValue: _i3.Stream<List<_i4.Sanction>>.empty(),
          )
          as _i3.Stream<List<_i4.Sanction>>);

  @override
  _i3.Future<void> addSanction(_i4.Sanction? s) =>
      (super.noSuchMethod(
            Invocation.method(#addSanction, [s]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSanction(_i4.Sanction? s) =>
      (super.noSuchMethod(
            Invocation.method(#updateSanction, [s]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSanction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSanction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Sanction>> fetchAll() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAll, []),
            returnValue: _i3.Future<List<_i4.Sanction>>.value(<_i4.Sanction>[]),
          )
          as _i3.Future<List<_i4.Sanction>>);

  @override
  _i3.Future<_i4.Sanction?> getSanctionByPoints(int? points) =>
      (super.noSuchMethod(
            Invocation.method(#getSanctionByPoints, [points]),
            returnValue: _i3.Future<_i4.Sanction?>.value(),
          )
          as _i3.Future<_i4.Sanction?>);
}
